### ISSUE TITLE
Can I borrow your awesome svg header? 😅

### ISSUE THREAD

**Issue by nourselim0** [aeneasr/aeneasr#1]
You made me discover that SVG can be animated with embedded CSS today, and I love it!
I looked at the SVG code and was quite impressed by how it worked and kept playing around it for half an hour.
I keep procrastinating making a nice README for my GitHub Profile, but when I do I'm thinking of using that same trick but with slightly different style and colors.
I don't know if you wrote that SVG yourself or used a tool, so I thought I should ask for permission first 😁

**Comment by aeneasr** [comment]
Please go ahead, I borrowed it myself :)

**Comment by nourselim0** [comment]
thank you 😁
